server:
  port: ${PORT}
spring:
  application:
    name: ${APP_NAME}
  webflux:
    base-path: ${BASE_PATH}
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
