server:
  port: 8080
spring:
  application:
    name: "pic-archetype"
  webflux:
    base-path: /demo
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
